### ISSUE TITLE
Not getting any Pyright warnings

### ISSUE THREAD

**Issue by shner-elmo** [InSyncWithFoo/pyright-for-pycharm#39]
### What happened?

Hey, so I followed the docs to install Pyright for PyCharm (community version), but I don't see any warnings/errors on this code:
![image](https://github.com/InSyncWithFoo/pyright-for-pycharm/assets/102916448/dc08f7f5-3c0c-47be-a7f8-58eafc277e29)

I'm not sure if I didn't install it correctly or there is a bug...

### Steps to reproduce

* Install the plugin trough Pycharm
* Configure the path: `pypoetry/virtualenvs/project-name/bin/pyright-python-langserver` (I tried all 3 pyright executables)
* Tried with and without passing the config file: `pyproject.toml`
* Check `Prefix with "Pyright: "`
* Disable `Incorrect type` in the inspections tab
* Enable `Pyright diagnostics`
* Restart PyCharm

### Operating system

Linux

**Comment by shner-elmo** [comment]
First of all, thanks for the swift response!

I tried all four; 
`pyright` and `pyright-python` were found, 
but for `pyright-langserver` and `pyright-python-langserver` the hint said: "Unrecognized filename (ignore this notice if you are sure it is correct)".

but anyways none of the 4 are working

**Comment by shner-elmo** [comment]
> Without the log, it is hard to say

How can I find it?

I can confirm that I now see the dot when I modify the file, and it disappears right away. However I don't see any Pyright warnings.

Is the only option left is to reinstall the IDE?

**Comment by shner-elmo** [comment]
Ok thanks for the explanation, I will try that tomorrow

**Comment by shner-elmo** [comment]
From the logs it seems like it is indeed running, and there is no `ProcessNotCreatedException`.

Here is the [output](https://pastebin.com/DxtQcbSB) of `grep -ir "pyright" ~/.cache/JetBrains/PyCharmCE2024.1/log` if you're interested.

**Comment by shner-elmo** [comment]
I reset the settings and reinstalled the IDE, still not working :(

**Comment by shner-elmo** [comment]
This is the output:
```
/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/nodeenv.py:48: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
 * Environment already exists: /home/shneor/.cache/pyright-python/nodeenv
Traceback (most recent call last):
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/bin/pyright-python", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/cli.py", line 25, in run
    pkg_dir = install_pyright(args, quiet=None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/_utils.py", line 64, in install_pyright
    node.run(
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/node.py", line 105, in run
    binary = _ensure_available(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/node.py", line 38, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/node.py", line 65, in _ensure_node_env
    _install_node_env()
  File "/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/lib/python3.11/site-packages/pyright/node.py", line 98, in _install_node_env
    subprocess.run(args, check=True)
  File "/home/shneor/.pyenv/versions/3.11.4/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/shneor/.cache/pypoetry/virtualenvs/tradingview-screener-5WV6isL9-py3.11/bin/python', '-m', 'nodeenv', '/home/shneor/.cache/pyright-python/nodeenv']' returned non-zero exit status 2.
```

**Comment by shner-elmo** [comment]
Ah yes! its working now:

![image](https://github.com/InSyncWithFoo/pyright-for-pycharm/assets/102916448/6b8b6360-4b04-458c-841b-b7da640434b5)

Turns out that doing `pip install pyright` isn't enough. You need to install npm and node.
FYI it might be easier to debug pyright issues by just invoking the executable: `$ pyright` and googling the rest...

Thanks again for all the help @InSyncWithFoo
