### ISSUE TITLE
Run PyRight with a Docker environment

### ISSUE THREAD

**Issue by jlucasp25** [InSyncWithFoo/pyright-for-pycharm#50]
Is it possible to run PyRight using this plugin for a interpreter running inside a Docker container?

**Comment by jlucasp25** [comment]
Thank you for the quick response. I'll look into it.

**Comment by lorisgir** [comment]
Hi, I'm also interested in running it inside a docker environment.

Have you found any solutions?

**Comment by lorisgir** [comment]
I just reverted to a local environment to make it work, U'll stay with this conf for now.
What's the difference between running mode command line and lsp4ij?
'Cause if I choose the latter i get this error:
`com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[/Users/lorisgir/Talkkit/backend/src/venv/bin/pyright-langserver, --stdio], workingDir=/Users/lorisgir/Talkkit/backend/src]
	at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$0(LanguageServerWrapper.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)`

**Comment by ReHoss** [comment]
> I just reverted to a local environment to make it work, I'll stay with this conf for now. A question if I may, what's the difference between running mode command line and lsp4ij? 'Cause if I choose the latter i get this error:
> 
> `com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[/Users/lorisgir/Talkkit/backend/src/venv/bin/pyright-langserver, --stdio], workingDir=/Users/lorisgir/Talkkit/backend/src] at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88) at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$0(LanguageServerWrapper.java:243) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)`

In my use case, it is very difficult to have a local virtual environment containing the libraries in the docker image.

**Comment by fellhorn** [comment]
I faced a similar challenge when using the extension with a remote environment and connecting `pright-langserver` via ssh. As communication with the server happens through stdio streams, one can also pass it through `docker`:

```shell
#!/usr/bin/env bash
# Replace 656bc with your container ID
docker exec -i 656bc /usr/local/bin/pyright-langserver $*
```

or the equivalent `docker run` command if you want to start the langserver in its own container.

Save the script somewhere and set the `Language server executable` accordingly.

For local imports one will need to handle workspace mounting and potentially the `PYTHONPATH` but this script should give a hint how to start.
