### ISSUE TITLE
Cannot parse process output

### ISSUE THREAD

**Issue by PowerSlime** [InSyncWithFoo/pyright-for-pycharm#59]
### What happened?

Can't use neither https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm neither this one plugin in PyCharm Professional.

Always get "Cannot parse process output" "Output is blank." from the IDE.

Tried to install it as npm global package, as pip dependency - end result always the same.

PyCharm 2024.1.4 (Professional Edition)
Arch Linux
Pyright 1.1.374
Python 3.12.2
Pip 23.2.1

If I run it via terminal - it works.

![image](https://github.com/user-attachments/assets/4ed55568-55d5-48e1-9e67-a5bfe1c7e7bc)

![image](https://github.com/user-attachments/assets/8aee5046-4469-457e-8d87-86eb9f7956a2)
![image](https://github.com/user-attachments/assets/689fc940-d28a-4866-9aa0-1f26613ed98a)

![image](https://github.com/user-attachments/assets/ac20ffb1-b84a-49a0-9cc3-7a3e031a21d7)
![image](https://github.com/user-attachments/assets/da890964-bfd6-42f9-ac73-2b53c5807acc)

### Steps to reproduce

1. Install Pyright plugin from IDE's marketplace
2. Open IDE settings and set it up as on screenshots
3. Check it on some code

### Relevant log output or stack trace

```text
(venv) [powerslime@desktopus fastapi-the-complete-course]$ whereis pyright
pyright: /home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/pyright
(venv) [powerslime@desktopus fastapi-the-complete-course]$ pyright test_file.py 
/home/powerslime/Dev/python-projects/fastapi-the-complete-course/test_file.py
  /home/powerslime/Dev/python-projects/fastapi-the-complete-course/test_file.py:22:17 - error: Argument missing for parameter "id" (reportCallIssue)
1 error, 0 warnings, 0 informations
```

### Operating system

Linux

**Comment by PowerSlime** [comment]
Sorry for long response. Here they are:

https://gist.github.com/PowerSlime/8e0d596ef888ea97abb8100e5330d9a4

Command:
```
/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/pyright --outputjson --project /home/powerslime/Dev/python-projects/fastapi-the-complete-course --pythonpath /home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/python /home/powerslime/Dev/python-projects/fastapi-the-complete-course/test_file.py
```

Btw, if I run it in console - it works, has some output.
```
(venv) [powerslime@desktopus fastapi-the-complete-course]$ /home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/pyright --outputjson --project /home/powerslime/Dev/python-projects/fastapi-the-complete-course --pythonpath /home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/python /home/powerslime/Dev/python-projects/fastapi-the-complete-course/test_file.py
{
    "version": "1.1.374",
    "time": "1722580277668",
    "generalDiagnostics": [
        {
            "file": "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/test_file.py",
            "severity": "error",
            "message": "Argument missing for parameter \"id\"",
            "range": {
                "start": {
                    "line": 21,
                    "character": 16
                },
                "end": {
                    "line": 21,
                    "character": 93
                }
            },
            "rule": "reportCallIssue"
        }
    ],
    "summary": {
        "filesAnalyzed": 1,
        "errorCount": 1,
        "warningCount": 0,
        "informationCount": 0,
        "timeInSec": 0.755
    }
}
```

**Comment by PowerSlime** [comment]
Error is slightly different now.
![image](https://github.com/user-attachments/assets/00a5d2da-3710-4ec3-916c-45f7bf3e7e42)


```
 * Environment already exists: /home/powerslime/.cache/pyright-python/nodeenv
Traceback (most recent call last):
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/cli.py", line 34, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/cli.py", line 19, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/cli.py", line 30, in run
    return node.run('node', str(script), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/node.py", line 105, in run
    binary = _ensure_available(target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/node.py", line 38, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/node.py", line 65, in _ensure_node_env
    _install_node_env()
  File "/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/lib/python3.12/site-packages/pyright/node.py", line 98, in _install_node_env
    subprocess.run(args, check=True)
  File "/home/powerslime/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/powerslime/Dev/python-projects/fastapi-the-complete-course/venv/bin/python', '-m', 'nodeenv', '/home/powerslime/.cache/pyright-python/nodeenv']' returned non-zero exit status 2.
```

And logs in case you need them: https://gist.github.com/PowerSlime/e3c297bc30e774e56007a27ec5981ab8

I see that it tries to call nodejs (if I understood correctly). Can somehow `nvm` cause that issue? Because I don't have node installed on global level, it's on user's one.

```
[powerslime@desktopus ~]$ nvm --version
0.39.7
[powerslime@desktopus ~]$ node -v
v20.10.0
[powerslime@desktopus ~]$ npm -v
10.2.5
[powerslime@desktopus ~]$ whereis node 
node: /home/powerslime/.nvm/versions/node/v20.10.0/bin/node
```

**Comment by PowerSlime** [comment]
Omg... Yes... Installing node on system level - solves the issue.
![image](https://github.com/user-attachments/assets/9b8114ba-a997-4c67-973f-127e79bab041)

For other who might face the same issue - just do `sudo pacman -S nodejs` 

Then I have question... Should I ask help from Microsoft itself, to add support for `nvm` and other tools, or here you have some idea how it could be fixed?

Or I just have to find a way how to have 2 different nodejs versions running on my machine, where necessary - nvm one, otherwise - global one :thinking:
