### ISSUE TITLE
Unable to start language server

### ISSUE THREAD

**Issue by lorisgir** [InSyncWithFoo/pyright-for-pycharm#69]
### What happened?

I setup the plugins executable to a local environment and set the running mode option to lsp4ij but then I got this error:

com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[/Users/lorisgir/Talkkit/backend/src/venv/bin/pyright-langserver, --stdio], workingDir=/Users/lorisgir/Talkkit/backend/src] at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88) at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$0(LanguageServerWrapper.java:243) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

### Steps to reproduce

Just setup the plugin executable paths and then i get the error

### Operating system

None

**Comment by lorisgir** [comment]
Here's the output:

`
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- /Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js
- /Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/langserver.index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.7975 (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js:1:559)
    at o (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js:1:1145)
    at Object.4111 (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/vendor.js:2:781539)
    at o (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js:1:1145)
    at Object.3009 (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-internal.js:1:1484269)
    at o (/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js:1:1145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/dist/pyright-langserver.js',
    '/Users/lorisgir/.cache/pyright-python/1.1.379/node_modules/pyright/langserver.index.js'
  ]
}
`

Is there any package I need to install first?

**Comment by lorisgir** [comment]
Ok so the problem was in fact nvm, the default version was 14. Now the output of that command is as you wrote earlier.
One more question, is it possibile to analyze with pyright the whole project and not going every single file?
I'd like to have the red underline under the file names in the project tree that have errors so I can fix them.

**Comment by fellhorn** [comment]
When using the plugin on a Linux machine, I saw issues with the `PATH` priority. Somehow the system `node` was used instead of the one installed via `nvm` although it has lower priority in the `PATH` setting.
Uninstalling the system's `node` resolved the issue. Especially Ubuntu has some rather ancient `node`.

**Comment by fellhorn** [comment]
@InSyncWithFoo You are right, sorry for my erroneous comment. The plugin works flawlessly here.

It has been a while that I used `nvm` + `npx`. My personal `nvm` installation seems to be broken as it is not in ~/.profile` and thus PyCharm only had the correct `PATH` when starting from a shell.

Additionally I was unaware that `npx` is just a `js` script using the system node:
```
~/.nvm/versions/node/v23.5.0/bin/npx pyright
```
still uses the wrong node version.

One would need to provide absolute paths to the `node` binary and the `pyright`/`pyright-langserver` script.

@InSyncWithFoo Thanks for your quick reply and sorry once again for wasting your time. Happy holidays and thanks for the work you put in this repo!
